export const SHOW_COMMON_ALERT = 'SHOW_COMMON_ALERT';
export const HIDE_COMMON_ALERT = 'HIDE_COMMON_ALERT';

//Contracts
export const GET_CONTRACTS = 'GET_CONTRACTS ';
export const GET_CONTRACTS_REQUEST = 'GET_CONTRACTS_REQUEST';
export const GET_CONTRACTS_COUNT = 'GET_CONTRACTS_COUNT ';
export const SET_CONTRACTS_COUNT = 'SET_CONTRACTS_COUNT ';
export const GET_CONTRACTS_COUNT_REQUEST = 'GET_CONTRACTS_COUNT_REQUEST';
export const SEARCH_CONTRACTS = 'SEARCH_CONTRACTS ';
export const SEARCH_CONTRACTS_REQUEST = 'SEARCH_CONTRACTS_REQUEST';
export const SET_SELECTED_CONTRACT = 'SET_SELECTED_CONTRACT';
